### PR TITLE
shared new solution on challenge wc

### PR DESCRIPTION
**Pull request by azie-ginanjar**

### CODE REVIEW

**Review by JohnCrickett — CHANGES_REQUESTED** [review]
Please only add your solution without reformatting everything else.

**Review by JohnCrickett — CHANGES_REQUESTED** [review]
Please only add a single line entry.

**Comment by azie-ginanjar** [comment]
updated, sorry I didn't noticed that my ide reformatting the code

**Review by JohnCrickett — APPROVED** [review]
Many thanks for updating

**Pull request merged**
