### PR TITLE
JSON Parser Golang

### PR DESCRIPTION
**Pull request by pasDamola**
Added changes to the json-parser challenges file. Thank you!

### CODE REVIEW

**Review by JohnCrickett — CHANGES_REQUESTED** [review]
Please only add a single line

**Comment by pasDamola** [comment]
Sorry, I'm not sure I understand. I added only a single line

**Comment by JohnCrickett** [comment]
Please check the diff, you've also reformatted the code.

**Comment by JohnCrickett** [comment]
Closed and manually added.

**Pull request closed without merging**
